services:
  - type: web
    name: IBD-Medical-Report-Classifier
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    build:
      systemPackages:
        - tesseract-ocr
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
