services:

type: web
name: IBD-Medical-Report-Classifier
runtime: python
plan: free

buildCommand: "pip install -r requirements.txt"

startCommand: "gunicorn app:app"

envVars:

key: TESSERACT_PATH
value: /usr/bin/tesseract
